import "./node_modules/bootstrap/dist/js/bootstrap.js";
import "./node_modules/bootstrap/dist/css/bootstrap.min.css";
import "./style.css";
import Navigo from "navigo";
import { HomePage } from "./src/pages/HomePage.js";
import { AboutPage } from "./src/pages/AboutPage.js";
import { render } from "./src/utils/common.js";
const app = document.getElementById("app");
const router = new Navigo("/", { linksSelector: "a" });
router.on("/home", () => render(app, HomePage));
router.on("/about", () => render(app, AboutPage));
router.resolve();
